interface RouteDesc {
  url: string // 描述了路由的path信息
  name: string // 描述了该路由所对应的中文名
  imgSrc: string // 图片链接
}

const InitAppRoutes: RouteDesc[] = [
  { url: '/', name: '文章管理', imgSrc: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAaVBMVEUAAAAsLCwsLCwsLCwsLCwrKyssLCwsLCwsLCwsLCwrKyssLCwtLS0oKCgsLCwsLCwsLCwrKyssLCwsLCwsLCwrKysrKysrKyssLCwpKSktLS0sLCwtLS0sLCwrKystLS0sLCwAAAAsLCzYs8ySAAAAInRSTlMAv4BAuJjzxu3V31ZNDuXar6SQi3pwajIoGc7JsayHYV0CJY/VGQAAALZJREFUOMvt0skSgjAQRdFHSAijzCDOvv//SBUKAhhYuvKuUl2nsuhqvEtE5tMUtFgWB15+E2M5w4OLea2vE5hcPk5ePAcFj1gAtzszgumSYgXw1LybieOswWfIZh9Ast4HyFjtAygKK0hYYkiwsQFoupOobSDmtJiClQVAHHgtRV/q2AA6IT0OGWDP+YOfAqm3gZYAlL8NfNXfjYItc5YBI1iLGAwPyVCJr1RIOVJzQbM82f//At+HDX0b8ggHAAAAAElFTkSuQmCC' },
  { url: '/tag', name: '标签管理', imgSrc: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAXVBMVEUAAAAsLCwsLCwsLCwrKystLS0rKysrKysrKysrKyssLCwrKyssLCwtLS0sLCwqKiotLS0sLCwsLCwrKyssLCwsLCwtLS0rKystLS0zMzMsLCwsLCwrKystLS0sLCxcyzcPAAAAHnRSTlMA5IC/P9TfqqIp27KLiVMYEtBnWbmbcWEzBfmSh0mC+GzWAAAA00lEQVQ4y9WRSQ6DMBRD/QMkTGVoy9TB9z9mVRIgbSNWbOqVLT0l+jYOkdGclah3UuLSGU4lV52AdEvKAcLYmpgC6CVdGDmAxOr89F9Asp2ZBM9UXjXBonBy5ebVV9XHqRR/TUAZ0engre2taa+aVayA/lgTV0ZxU1fCEsGiFDuUYgChCgIFY0MaoGcXBISN/TNjEQQ06yjFDJggkLJaFngEgTNlCc91zYs1A3MALaXPRkXm08+a9vWr9TdGtb+mX3Uh+T2bNNsGe6pbZthVM+IIvQAzDR2Hnn7qVgAAAABJRU5ErkJggg==' },
]

export {
  InitAppRoutes,
}
